provision:
  image: nathanleclaire/ansibleprovision
  net: host
  volumes:
    - /root/.ssh:/hostssh
  labels:
    - "com.nathanleclaire.ansibleprovison"
  environment:
    - affinity:label!=com.nathanleclaire.ansibleprovision
consul:
  image: progrium/consul
  hostname: consul
  command: -server -bootstrap
  ports:
    - "8500:8500"
